// This file is generated by i18n/plural/codegen/generate.sh; DO NOT EDIT

package plural

// DefaultRules returns a map of Rules generated from CLDR language data.
func DefaultRules() Rules { _ = "STUB: not implemented"; return *new(Rules) }

// i = 0 or n = 1

// i = 0,1

// i = 1 and v = 0

// n = 0,1 or i = 0 and f = 1

// n = 0..1

// n = 0..1 or n = 11..99

// n = 1

// n = 1 or t != 0 and i = 0,1

// t = 0 and i % 10 = 1 and i % 100 != 11 or t % 10 = 1 and t % 100 != 11

// v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11

// v = 0 and i = 1,2,3 or v = 0 and i % 10 != 4,6,9 or v != 0 and f % 10 != 4,6,9

// n % 10 = 0 or n % 100 = 11..19 or v = 2 and f % 100 = 11..19

// n % 10 = 1 and n % 100 != 11 or v = 2 and f % 10 = 1 and f % 100 != 11 or v != 2 and f % 10 = 1

// n = 0

// i = 0,1 and n != 0

// n = 0

// n = 1

// i = 1 and v = 0 or i = 0 and v != 0

// i = 2 and v = 0

// n = 1

// n = 2

// i = 0 or n = 1

// n = 2..10

// i = 1 and v = 0

// v != 0 or n = 0 or n != 1 and n % 100 = 1..19

// v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11

// v = 0 and i % 10 = 2..4 and i % 100 != 12..14 or f % 10 = 2..4 and f % 100 != 12..14

// i = 0,1

// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5

// i = 0..1

// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5

// i = 1 and v = 0

// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5

// n = 1

// e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5

// n = 1,11

// n = 2,12

// n = 3..10,13..19

// v = 0 and i % 100 = 1

// v = 0 and i % 100 = 2

// v = 0 and i % 100 = 3..4 or v != 0

// v = 0 and i % 100 = 1 or f % 100 = 1

// v = 0 and i % 100 = 2 or f % 100 = 2

// v = 0 and i % 100 = 3..4 or f % 100 = 3..4

// i = 1 and v = 0

// i = 2..4 and v = 0

// v != 0

// i = 1 and v = 0

// v = 0 and i % 10 = 2..4 and i % 100 != 12..14

// v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14

// n % 10 = 1 and n % 100 != 11

// n % 10 = 2..4 and n % 100 != 12..14

// n % 10 = 0 or n % 10 = 5..9 or n % 100 = 11..14

// n % 10 = 1 and n % 100 != 11..19

// n % 10 = 2..9 and n % 100 != 11..19

// f != 0

// v = 0 and i % 10 = 1 and i % 100 != 11

// v = 0 and i % 10 = 2..4 and i % 100 != 12..14

// v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14

// n % 10 = 1 and n % 100 != 11

// n = 2

// n != 2 and n % 10 = 2..9 and n % 100 != 11..19

// f != 0

// n % 10 = 1 and n % 100 != 11,71,91

// n % 10 = 2 and n % 100 != 12,72,92

// n % 10 = 3..4,9 and n % 100 != 10..19,70..79,90..99

// n != 0 and n % 1000000 = 0

// n = 1

// n = 2

// n = 0 or n % 100 = 3..10

// n % 100 = 11..19

// n = 1

// n = 2

// n = 3..6

// n = 7..10

// v = 0 and i % 10 = 1

// v = 0 and i % 10 = 2

// v = 0 and i % 100 = 0,20,40,60,80

// v != 0

// n = 0

// n = 1

// n % 100 = 2,22,42,62,82 or n % 1000 = 0 and n % 100000 = 1000..20000,40000,60000,80000 or n != 0 and n % 1000000 = 100000

// n % 100 = 3,23,43,63,83

// n != 1 and n % 100 = 1,21,41,61,81

// n = 0

// n = 1

// n = 2

// n % 100 = 3..10

// n % 100 = 11..99

// n = 0

// n = 1

// n = 2

// n = 3

// n = 6
